# Generated by Django 4.2.5 on 2023-09-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_comment_book_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_recommended',
            field=models.BooleanField(default=True),
        ),
    ]
