# Generated by Django 4.2.5 on 2023-09-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='creator',
            new_name='user',
        ),
    ]
